# Project: ArvoreBinaria
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mainArvoreBinaria.o Arvore.o
LINKOBJ  = mainArvoreBinaria.o Arvore.o
LIBS     = -L"C:/Users/usuario/Desktop/Pastas/DEV-C++/Dev-Cpp/MinGW64/lib" -L"C:/Users/usuario/Desktop/Pastas/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/usuario/Desktop/Pastas/DEV-C++/Dev-Cpp/MinGW64/include" -I"C:/Users/usuario/Desktop/Pastas/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/usuario/Desktop/Pastas/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/usuario/Desktop/Pastas/DEV-C++/Dev-Cpp/MinGW64/include" -I"C:/Users/usuario/Desktop/Pastas/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/usuario/Desktop/Pastas/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/usuario/Desktop/Pastas/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ArvoreBinaria.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

mainArvoreBinaria.o: mainArvoreBinaria.c
	$(CC) -c mainArvoreBinaria.c -o mainArvoreBinaria.o $(CFLAGS)

Arvore.o: Arvore.c
	$(CC) -c Arvore.c -o Arvore.o $(CFLAGS)
